databases:
  - name: fimani-quiz-db
    plan: free
    databaseName: fimani_quiz
    user: fimani

services:
  - type: web
    name: fimani-quiz
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: fimani-quiz-db
          property: connectionString
      - key: ADMIN_TOKEN
        value: 38L-YRkLfziplGFf
      - key: RESEND_API_KEY
        sync: false
      - key: NOTIFY_EMAIL
        sync: false
